### ISSUE TITLE
Tablet menu is not showing correctly

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-velux-theme#22]
Tested on iPad air.

<img width="765" alt="screen shot 2016-08-09 at 12 41 41 pm" src="https://cloud.githubusercontent.com/assets/1933681/17524983/c3445722-5e2e-11e6-9242-91116c48842b.png">

**Comment by mrpritchett** [comment]
@jonathanbardo Please confirm that this is now fixed at http://liftux.wpengine.com/velux/

![screen shot 2016-08-09 at 1 25 08 pm](https://cloud.githubusercontent.com/assets/3329081/17526321/b766e982-5e34-11e6-9004-3b2302c9ef0a.png)

**Comment by jonathanbardo** [comment]
@mrpritchett It's fixed on portrait. I still see the same issue on landscape iPad air.
<img width="1018" alt="screen shot 2016-08-09 at 1 28 14 pm" src="https://cloud.githubusercontent.com/assets/1933681/17526408/272bf3de-5e35-11e6-9e00-e57973046c14.png">

**Comment by mrpritchett** [comment]
Ok. I reworked most of the breakpoints for that section and tested in across a plethora of sizes. Please confirm. @jonathanbardo

**Comment by jonathanbardo** [comment]
It seems the site title and site description is now on the right for portrait? Was that intended?
<img width="765" alt="screen shot 2016-08-09 at 1 58 29 pm" src="https://cloud.githubusercontent.com/assets/1933681/17527501/9a0a4ce4-5e39-11e6-81b2-884c432de55e.png">

**Comment by mrpritchett** [comment]
Yes. That was how it was supposed to be. It was being pushed over by the previous issue.

**Comment by jonathanbardo** [comment]
All good then. Thanks!
